image: python:3.7

before_script:
  #- apt-get update >/dev/null
  #- apt-get install -y locales >/dev/null
  #- echo "en_US UTF-8" > /etc/locale.gen
  #- locale-gen en_US.UTF-8
  #- export LANG=en_US.UTF-8
  #- export LANGUAGE=en_US:en
  #- export LC_ALL=en_US.UTF-8

  #- apt-get update && apt-get install python3 python3-pip python3-dev -y
  - pip3 install -r requirements.txt
  - cd src
  - pip3 install -e .

flask_tests:
  script:
    - python3 --version
    - pytest --cov=flaskr tests/
  #only:
    #- master
    #- development
    #- test-ci
