"""empty message

Revision ID: a97b80c3c059
Revises: 
Create Date: 2019-02-22 14:49:57.295894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a97b80c3c059'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('adminid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('adminid')
    )
    op.create_index(op.f('ix_admin_user_username'), 'admin_user', ['username'], unique=True)
    op.create_table('frontpage_post',
    sa.Column('made', sa.Date(), nullable=False),
    sa.Column('body_text', sa.String(length=400), nullable=False),
    sa.PrimaryKeyConstraint('made', 'body_text')
    )
    op.create_table('job_applicant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('CV', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_positions',
    sa.Column('job_positions_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('made', sa.Date(), nullable=True),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('contact_mail', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('job_positions_id')
    )
    op.create_table('startup',
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('startup_id')
    )
    op.create_table('tag',
    sa.Column('tagname', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('tagname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    op.drop_table('startup')
    op.drop_table('job_positions')
    op.drop_table('job_applicant')
    op.drop_table('frontpage_post')
    op.drop_index(op.f('ix_admin_user_username'), table_name='admin_user')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
